services:
  nats:
    image: nats:2-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command: --http_port 8222

  streaming-service:
    build: ./service
    ports:
      - "3000:3000"
    environment:
      NATS_URL: nats://nats:4222
      NUM_CHANNELS: "20"
      DATA_RATE_MS: "250"
    depends_on:
      - nats
