[package]
name = "nemo-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nemo-plugin-api = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
